import { defineConfig } from 'astro/config';

// Tourist Pharmacy — static catalog + booking funnel.
// output: 'static' so the whole site deploys as a plain dist/ folder (any static host),
// and ships zero JS by default — critical for laggy Bali mobile connections.
// Sitemap is generated by src/pages/sitemap.xml.ts (custom, covers all product pages).
export default defineConfig({
  site: 'https://touristpharmacy.com',
  output: 'static',
  trailingSlash: 'ignore',
  build: {
    inlineStylesheets: 'auto',
  },
});
